# -*- coding: utf-8 -*-
"""SG_SA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11la-NieQXDOpEIv2X2l8-agUre1Lr5xU
"""

!pip install transformers gradio --quiet

# Imports
from transformers import pipeline
import gradio as gr
import random

# Load models
sentiment_pipeline = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")
emotion_pipeline = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", return_all_scores=False)

# Story templates
story_templates = {
    ("Positive", "Joy"): [
        "She danced barefoot in the grass, her heart lighter than air.",
        "The sun broke through the clouds just as he got the news. It felt like the universe was smiling with him."
    ],
    ("Negative", "Sadness"): [
        "He stared at the old photograph, wondering if time could ever rewind. The ache in his chest said no.",
        "The rain matched her mood—steady, relentless, and quietly devastating."
    ],
    ("Negative", "Anger"): [
        "She slammed the door, not to shut him out, but to keep herself from exploding.",
        "The injustice was too loud to ignore. He stood, trembling—not with fear, but fury."
    ],
    ("Neutral", "Confusion"): [
        "He stood at the crossroads, unsure which path led home—or if any did.",
        "Her thoughts tangled like vines, each one pulling her in a different direction."
    ],
    ("Neutral", "Neutral"): [
        "She stirred her coffee slowly, watching the steam rise. It was just another morning, and that was okay.",
        "The train arrived on time. He boarded, sat by the window, and watched the city blur into countryside."
    ],

}

# Story generator function
def generate_story(text):
    sentiment_result = sentiment_pipeline(text)[0]
    emotion_result = emotion_pipeline(text)[0]

    sentiment = sentiment_result['label'].capitalize()
    emotion = emotion_result['label'].capitalize()
    sentiment_score = sentiment_result['score']
    emotion_score = emotion_result['score']

    key = (sentiment, emotion)
    story_list = story_templates.get(key)

    if story_list:
        story = random.choice(story_list)
    else:
        story = "No story available for this sentiment-emotion combination."

    return (
        f"🧠 Sentiment: {sentiment} ({sentiment_score:.2f})\n"
        f"🎭 Emotion: {emotion} ({emotion_score:.2f})\n\n"
        f"📖 Story:\n{story}"
    )

# Gradio UI
gr.Interface(
    fn=generate_story,
    inputs=gr.Textbox(lines=3, placeholder="Type something emotional..."),
    outputs="text",
    title="🧠 Sentiment + Emotion Story Generator",
    description="Enter a sentence to detect sentiment and emotion, and receive a story that reflects both."
).launch()